name: CD-Backend

on:
  workflow_run:
    workflows:
      - CI-Backend
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    environment: Production

    steps:
      - name: Checkout Infra
        uses: actions/checkout@v4
        with:
          repository: anakbaik-code/devops-infra
          path: infra

      - name: Deploy Backend
        env:
          PORT: ${{ vars.PORT }}
        run: |
          docker compose \
          -f infra/docker-compose.yaml \
          up -d \
          --pull always \
          app-backend-1 \
          app-backend-2 \
          app-backend-3

      - name: Check Backend
        run: |
          docker compose \
          -f infra/docker-compose.yaml \
          ps \
          app-backend-1 \
          app-backend-2 \
          app-backend-3
